Merging all the work from Secondary to master branch for code review evaluation
memelopez/microV-wk1proj pull request #8
Opened 2021-01-20 23:55 UTC by memelopez

we started the project yesterday because of a confusion of ours, it still has to improve but we are submitting it for the sof deadline. 👍🏼

2021-01-22 20:02 UTC, memelopez commented
Our page looks crips, almost perfect. We have no linter errors and are ready for another code review.

2021-01-22 23:51 UTC, krys2fa requested changes
## Nicely done @memelopez  and @Fondem-Jr  👏 
Your project displays good use of semantic HTML as well as CSS classes. 💪 
You have a professional-looking README file as well. 👍 

Just a few more adjustments to complete the project. They can be seen below as well as in the comments:
### Status: Changes Required ♻️ 

**NB:** Review was done at a screen size of **1440px**. Kindly state your preferred screen size if your clone displays better on your machine.

- [ ] [REQUIRED] Elements should be aligned with a combination of all three techniques ([float](
https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction)). You need to use float as well.

- [ ] [OPTIONAL] It should have a fixed footer (i.e it should stick to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2021-01-22 23:51 UTC, krys2fa commented on README.md
> +
- [ ] [REQUIRED] Please provide the steps to take in order for the project to be setup. If no steps are required, you should remove these headings.

2021-01-23 01:47 UTC, memelopez commented
please review at a screen size of 1700px
The page uses:
- floats in the top right left plus icon in the 'newsletter' section
- position fixed on navbar and footer
- grid on the articles of the 'newsletter' and in the 'theory of inflation' section
- flexbox all throughout the layout of the page
- position absolute, relative different sections

2021-01-23 01:56 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @memelopez 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Remove commented CSS from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [x] MIT License giving 404 error. Please fix it.
- [x] Update css path. see inline comments
- [x] Please implement the previous TSE's suggestions about the README file
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-01-23 01:56 UTC, umairarshadbutt commented on css/style-storybody.css
> +/* #foraside {
Remove commented CSS

2021-01-23 01:56 UTC, umairarshadbutt commented on css/style-storybody.css
> +  /* width: 1200px; */
Remove commented CSS

2021-01-23 01:56 UTC, umairarshadbutt commented on css/styles-bottomNav.css
> +  /* display: inline-block; */
Remove commented CSS

2021-01-23 01:56 UTC, umairarshadbutt commented on css/styles-lowerFooter.css
> +  /* transform: translateY(-56px); */
Remove commented CSS

2021-01-23 01:56 UTC, umairarshadbutt commented on css/styles-mainHeader.css
> +  /* margin-right: 7px; */
Remove commented CSS

2021-01-23 01:56 UTC, umairarshadbutt commented on index.html
> +    <link rel="stylesheet" href="css/styles-recirc.css">
`href="css/styles-recirc.css"`  is not a correct path please use like `href="./css/styles-recirc.css"` (**update all links**)

2021-01-23 03:08 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 

Great job @team, lovely clone I liked it.

now you can merge your project is approved :checkered_flag: 

## Happy Coding :tophat:

2021-01-23 03:17 UTC, merged